apiVersion: v1
kind: Route
metadata:
  name: pyjwt-simple-app-route
spec:
  to:
    kind: Service
    name: pyjwt-simple-app-svc
---
kind: "Service"
apiVersion: "v1"
metadata:
  name: pyjwt-simple-app-svc
spec:
  selector:
    name: pyjwt-simple-app-dc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
---
kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: "pyjwt-simple-app-dc"
spec:
  template:
    metadata:
      labels:
        name: "pyjwt-simple-app-dc"
    spec:
      containers:
        - name: "pyjwt-simple-app"
          image: "ilysenkogd/pyjwt:demo"
          ports:
            - containerPort: 5000
              protocol: "TCP"
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
  replicas: 2
  strategy:
    type: "Rolling"
