kind: Route
apiVersion: v1
metadata:
  name: redis-route
spec:
  to:
    kind: Service
    name: redis-svc
---
kind: Service
apiVersion: v1
metadata:
  name: redis-svc
spec:
  selector:
    name: redis-dc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
---
kind: DeploymentConfig
apiVersion: v1
metadata:
  name: redis-dc
spec:
  template:
    metadata:
      labels:
        name: redis-dc
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 3306
              protocol: TCP
  replicas: 1
